name: Deploy

on:
  workflow_dispatch:
    inputs:
      git-commit:
        description: Git commit SHA (Optional)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository (Latest)
        uses: actions/checkout@v4
        if: github.event.inputs.git-commit == ''
      - name: Clone repository (Custom commit)
        uses: actions/checkout@v4
        if: github.event.inputs.git-commit != ''
        with:
          ref: ${{ github.event.inputs.git-commit }}
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: sam-simple-site-out
          path: out
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: sam-simple-site-out
          path: out
      - name: Upload files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'out'
