name: E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository (Latest)
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: npm install
        run: npm install
      - name: npm test
        run: npm run test:e2e
